excluded:
  - ${PWD}/Pods
disabled_rules:
  - line_length
  - type_body_length
  - identifier_name
  - multiple_closures_with_trailing_closure
  - void_function_in_ternary
opt_in_rules:
  - closure_spacing
  - closure_end_indentation
  - closure_body_length
  - collection_alignment
  - contains_over_filter_is_empty
  - contains_over_filter_count
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discouraged_object_literal
  - empty_count
  - empty_string
  - fallthrough
  - file_name_no_space
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - implicit_return
  - joined_default_parameter
  - last_where
  - literal_expression_end_indentation
  - no_extension_access_modifier
  - operator_usage_whitespace
  - redundant_optional_initialization
  - redundant_set_access_control
  - redundant_type_annotation
  - sorted_first_last
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - vertical_whitespace_opening_braces
  - legacy_multiple
  - legacy_random
analyzer_rules:
  - unused_declaration
  - unused_import
force_cast: error          # [NG] as!
force_unwrapping: error    # [NG] value!
